[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "gidconfig"
author = "Giddius"
classifiers = ["License :: OSI Approved :: MIT License"]
description-file = "readme.md"
requires = ["pytoml>=0.1.21"]




[tool.flit.scripts]

